title: TeachBook (Chemistry Sciences Template)
author: Álvaro Lozano Murciego and André Sales Mendes (USAL) built with a modified version of <a href="https://teachbooks.io/">TeachBooks</a>, <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="license noopener noreferrer"">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt=""></a>
copyright: "2026, Curso de Formación Docente"
logo: "_static/logo.png"
language: en
exclude_patterns: ["_build", "Thumbs.db", ".DS_Store", "**.ipynb_checkpoints", "_build_*", "es/","temp_build_*", "latex_templates*", "_TRASH*"]
execute:
  execute_notebooks: off
parse:
  myst_enable_extensions:
    - colon_fence
    - dollarmath
    - linkify
  use_download_button: true
  extra_navbar: |
    <div style="margin-top: 10px; font-size: 0.8em; color: #666;">
      Powered by <a href="https://jupyterbook.org">Jupyter Book</a>
    </div>
html_theme_options:
  icon_links: []
sphinx:
  config:
    html_js_files:
    - custom.js
latex_docclass:
  book: jupyterBook
latex:
  latex_engine: xelatex
  options: "english"
  preamble: |
    \usepackage[english]{babel}
    \selectlanguage{english}
